name: Laravel Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, bcmath, mysql
        coverage: none

    - name: Install Composer dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install npm dependencies
      run: npm install

    - name: Build Vite assets
      run: npm run build

    - name: Deploy to Server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: server50.shared.spaceship.host
        username: keclribpbb
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 65002
        script: |
          cd /home/keclribpbb/tattsvi.in
          git pull origin main
          php artisan migrate --force
          php artisan config:clear
          php artisan cache:clear
