name: Deploy Tattsvi Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: server50.shared.spaceship.host
          username: keclribpbb
          key: ${{ secrets.SSH_KEY }}
          port: 65002
          script: |
            cd /home/keclribpbb/tattsvi.in
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan config:clear
            php artisan cache:clear
            php artisan view:clear
