name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: server50.shared.spaceship.host
          username: keclribpbb
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /home/keclribpbb/tattsvi.in
            git pull origin main
